name: Application CI

on:
  pull_request:
    branches: [lumine]

jobs:
  web:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: ./web/yarn.lock

      - name: Install all frontend dependencies
        run: yarn --frozen-lockfile
        working-directory: ./web

      - name: Format and lint web frontend
        run: yarn lint
        working-directory: ./web

    api:
      runs-on: ubuntu-20.04

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Node
          uses: actions/setup-node@v2
          with:
            node-version: "16"
            cache: "yarn"
            cache-dependency-path: ./api/yarn.lock

        - name: Install all backend dependencies
          run: yarn --frozen-lockfile
          working-directory: ./api

        - name: Format and lint API backend
          run: yarn lint
          working-directory: ./api
