name: Node, Vercel, and Heroku

on:
  workflow_dispatch:
  push:
    branches: [lumine]

jobs:
  node:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: |
            ./web/yarn.lock
            ./api/yarn.lock

      - name: Install all frontend dependencies
        run: yarn --frozen-lockfile
        working-directory: ./web

      - name: Lint web frontend
        run: yarn lint
        working-directory: ./web

      - name: Install all backend dependencies
        run: yarn --frozen-lockfile
        working-directory: ./api

      - name: Lint API backend
        run: yarn lint
        working-directory: ./api

  vercel:
    runs-on: ubuntu-20.04
    needs: node

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy website (production version) to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod"
          working-directory: web

  heroku:
    runs-on: ubuntu-20.04
    needs: node

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build API, push to Heroku, and deploy on Heroku.
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: api
